Repository remusplesa/hackathon-accessibility-app, pull requests merged in 2022-11, with the labels that each got.

#1 UI Setup + File Upload Component
  accessible-places-frontend/.gitignore
  accessible-places-frontend/index.html
  accessible-places-frontend/package-lock.json
  accessible-places-frontend/package.json
  accessible-places-frontend/src/App.tsx
  accessible-places-frontend/src/components/ImageUpload/ImageUpload.tsx
  accessible-places-frontend/src/index.css
  accessible-places-frontend/src/logic/helpers/handleApolloError.ts
  accessible-places-frontend/src/logic/hooks/useUploadUrl.ts
  accessible-places-frontend/src/main.tsx
  accessible-places-frontend/src/vite-env.d.ts
  accessible-places-frontend/tsconfig.json
  accessible-places-frontend/tsconfig.node.json
  accessible-places-frontend/vite.config.ts
Labels: WIP | No-Merge

#2 Feat/map implementation
  accessible-places-backend/package-lock.json
  accessible-places-frontend/index.html
  accessible-places-frontend/package-lock.json
  accessible-places-frontend/package.json
  accessible-places-frontend/src/App.tsx
  accessible-places-frontend/src/main.tsx
  accessible-places-frontend/src/pages/MapPage/MapPage.styles.css
  accessible-places-frontend/src/pages/MapPage/MapPage.tsx
Labels: enhancement

#3 Setup GitHub login using Firebase
  accessible-places-frontend/package-lock.json
  accessible-places-frontend/package.json
  accessible-places-frontend/src/App.tsx
  accessible-places-frontend/src/components/AuthProvider.tsx
  accessible-places-frontend/src/components/PrivateRoute/PrivateRoute.tsx
  accessible-places-frontend/src/firebase.ts
  accessible-places-frontend/src/index.css
  accessible-places-frontend/src/main.tsx
  accessible-places-frontend/src/pages/LoginPage/LoginPage.tsx
  accessible-places-frontend/src/pages/MapPage/MapPage.tsx
Labels: enhancement

#9 Configure DNS to start on localhost
  accessible-places-frontend/src/components/AuthProvider.tsx
  accessible-places-frontend/vite.config.ts
Labels: bug

#8 Feat/map implementation
  accessible-places-frontend/package-lock.json
  accessible-places-frontend/src/App.tsx
  accessible-places-frontend/src/AppRouter.tsx
  accessible-places-frontend/src/Context/SideDrawerContext/SideDrawerContext.tsx
  accessible-places-frontend/src/components/SideDrawer/SideDrawer.tsx
  accessible-places-frontend/src/pages/MapPage/MapPage.styles.css
  accessible-places-frontend/src/pages/MapPage/MapPage.tsx
Labels: enhancement

#12 Steps Component | Chakra UI
  accessible-places-frontend/package-lock.json
  accessible-places-frontend/package.json
  accessible-places-frontend/src/components/MenuLinks/MenuLinks.tsx
  accessible-places-frontend/src/components/Steps/Steps.styles.css
  accessible-places-frontend/src/components/Steps/Steps.tsx
  accessible-places-frontend/src/pages/UploadPage/UploadPage.tsx
Labels: enhancement
